steps:
  - label: "build collector layer"
    commands:
      - cd collector
      - apt install -y zip
      - make package
    artifact_paths: "build/collector-extension.zip"
    plugins:
      - docker#v3.9.0:
          image: "golang:1.18-bullseye"

  - label: "build wrapper layer"
    commands:
      - cd nodejs
      - npm install
    artifact_paths: "packages/layer/layer.zip"
    plugins:
      - docker#v3.9.0:
          image: "node:16"