steps:
  - label: "build collector layer"
    commands:
      - cd collector
      - make package
    artifact_paths: "collector/build/collector-extension.zip"
    plugins:
      - docker#v3.9.0:
          image: "golang:1.18-bullseye"

  - label: "build wrapper layer"
    commands:
      - cd nodejs
      - npm install
    artifact_paths: "nodejs/packages/layer/layer.zip"
    plugins:
      - docker#v3.9.0:
          image: "node:16"